### ISSUE TITLE
Watcher sends wrong Kyma object key to the listener after recent remote changes

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/runtime-watcher#103]
**Description**
Currently, The runtime-watcher component sends the remote object key of the watched resource to the listener to be re-queued. Which doesn't work when the remote object key is not the same as the object key of the KCP resource. This is especially true in the case of synchronized Kyma CRs.

**Expected result**
`kcp-system/kyma-sample` should be enqueued

**Actual result**
`kyma-system/default` is enqueued instead

**Comment by jeremyharisch** [comment]
Fixed with https://github.com/kyma-project/runtime-watcher/pull/104
