### ISSUE TITLE
Retry sendRequestToKcp in case failure

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/runtime-watcher#132]
When the `sendRequestToKcp` function fails to receive a response from KCP, it's essential to implement a retry mechanism to enhance the robustness of the watcher component. This will ensure that webhook requests are retried several attempt before considering the operation as failed.

AC:

- [x] Implement a retry mechanism for webhook requests to KCP in case of failure. Retry up to a maximum of three times to improve reliability.
- [x] Modify the `sendRequestToKcp` function to return `(string, error)` instead of just `string` to have better error handling and reporting.

**Comment by LeelaChacha** [comment]
Second AC is invalid. The function already returns an error object
