### ISSUE TITLE
Introduce Versioning to the Watcher

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/runtime-watcher#134]
**Description**

Now watcher should be ready to release on PROD, but we still lacking of the process to alignment watcher versioning on Lifecycle manager release.

The Release Process concludes with the following:
- Only keep on branch `main`; no release branches
- Release always from `main`
- Introduce semantic versioning incl. Release notes
- No regular releases

**ACs**
- [ ] Introduce Prow release pipeline triggered using tags
    - [ ] You can use CLI prow pipeline as inspiration `rel-kyma-cli`
    - [ ] Align with team Neighbours how to tag image with semantic versioning ([hint](https://github.com/kyma-project/test-infra/blob/f1771f2a542596f6fcbf721746fb975e2c83bf9f/cmd/image-builder/main.go#L458))
    - [ ] Stick with prow to build image, since this has signing mechanism
- [ ] Release notes should be created automatically using goreleaser
    - [ ] [hint](https://github.com/kyma-project/cli/blob/main/hack/release.sh) using similar as make target and called in pipeline

**Comment by Tomasz-Smelcerz-SAP** [comment]
I think the ACs for the `goreleaser` are not relevant anymore. We can't use the same process as the CLI, we have to use secured environment for building and publishing the artifacts.
Using `goreleaser` just to provide the changelog doesn't make much sense as there are many other ways to produce the changelog.
