### ISSUE TITLE
Metrics: Introduce runtime-Watcher metrics

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/runtime-watcher#146]
**Description**
At the moment, the runtime-watcher does not have any metrics.

**Acceptance Criterias**
- [x] Introduce metrics for runtime-watcher
    - [x] failed-requests send to KCP
    - [x] requests-total send to KCP
    - [x] request-duration to KCP
    - [x] Validation Requests to Runtime-Watcher
    - [x] Webhook-errors (erros which happen [here](https://github.com/kyma-project/runtime-watcher/blob/main/runtime-watcher/internal/parser/parser.go#L26))
    - [x] Which Watcher version is running
    - [x] ... (come up with more we can make use of)
- [x] Clarify with SREs if we can leverage current solution which is used by other modules
    - [x] Check what the solution is and if we can use it as well
    - [x] Prepare knowledge sharing for the team, how it works
- [x] Introduce new Plutono dashboard to collect those metrics
    - [x] Compare difference between TotalRequests to ValdiationRequests -> should be equal, to not make sure have have internal runtime-watcher errors

**Comment by lindnerby** [comment]
Metrics are visible in [dashboard](https://plutono.cp.stage.kyma.cloud.sap/d/O3DH7uunk/lifecycle-manager-overview?orgId=1&from=now-6h&to=now#:~:text=SKR%2D-,Webhook,-AdmissionRequest%20Duration).
