### ISSUE TITLE
Watcher: Revisit the kcp configuration and devise a persistent merge logic

### ISSUE THREAD

**Issue by adityabhatia** [kyma-project/runtime-watcher#16]
Watcher CRs are planned to be created by each operator running in the KCP. Each of these CRs should provide a list of GVKs of resources, along with the respective resources fields to watch for.
As part of this backlog item:

- [ ] Merge configuration logic
- [ ] Implement caching of already merged configuration. Unchanged CRs should not be merged again.

**Comment by jakobmoellersap** [comment]
Can we extend this issue a bit? I have trouble understanding what is necessary here in terms of architecture

**Comment by khlifi411** [comment]
Merge logic is not needed anymore as we will deploy the same KCP `watch` configuration on all `SKR`s
