### ISSUE TITLE
runtime-watcher(MVP): Implement OCI bundle which enables the Module-Manager to install the Watcher component

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/runtime-watcher#3]
**Description**

Generate an OCI image which includes all necessary information for the Manifest Operator to install the Watcher component in a remote cluster.

AC:
- [ ] HELM Chart is created to install the Watcher component in a remote cluster
- [ ] CI/CD pipeline is implemented to generate a new OCI image (use [Kyma CLI](https://github.com/kyma-project/cli/issues/1325) for generating the OCI image) for each code change pushed to the Kyma-Watcher repository
    - [ ] Populate generated OCI image into a Kyma channel

**Comment by tobiscr** [comment]
Blocked by https://github.com/kyma-project/cli/issues/1317

**Comment by jakobmoellersap** [comment]
In the template operator we have the necessary scripts to make this run without any additional effort => if we adjust the watcher to be compliant with out template operator scaffolding the first point should be a quick win

**Comment by tobiscr** [comment]
Collides with https://github.com/kyma-project/runtime-watcher/issues/70
