### ISSUE TITLE
Remove replacements for `golang.org/x/net`

### ISSUE THREAD

**Issue by c-pius** [kyma-project/runtime-watcher#402]
## Description

We added replacements for `golang.org/x/net` to solve security vulnerabilities coming from indirect dependencies. We need to re-check if the origin dependencies have been updated in the meantime so we can revert the replacements.

## AC

- [ ] replacement removed in both listener and runtime-watcher
- [ ] using the up to date dependency without security vulnerabilities

**Comment by lindnerby** [comment]
Closing this. Has been resolved by upgrading the dependency: https://github.com/kyma-project/runtime-watcher/pull/441
