### ISSUE TITLE
runtime-watcher: Make listener component an independent go project

### ISSUE THREAD

**Issue by adityabhatia** [kyma-project/runtime-watcher#45]
Listener is currently part of https://github.com/kyma-project/kyma-watcher/tree/main/kcp/pkg/listener. Since it is a dependency for all operators, like kyma-operator, manifest-operator, it should be an independent go package. 

AC:
- [x] Initialize a go project for listener in https://github.com/kyma-project/kyma-watcher/tree/main/listener and place relevant resources
- [x] Add relevant pipelines jobs for listener
- [x] Configure lint checks
- [x] Verify no dependency to other operators / libraries in kyma
- [ ] Update kyma-operator, manifest-operator and any other operator that might be using the listener component with the new module dependecy

**Comment by jakobmoellersap** [comment]
https://github.com/kyma-project/runtime-watcher/pull/48

**Comment by jeremyharisch** [comment]
PRs to upgrade the listener dependency:
- https://github.com/kyma-project/module-manager/pull/82
- https://github.com/kyma-project/lifecycle-manager/pull/143
- https://github.com/kyma-project/runtime-watcher/pull/60

PR to clean up the Watcher and the lsitener:
- https://github.com/kyma-project/runtime-watcher/pull/59/files
