### ISSUE TITLE
runtime-watcher: E2E tests Improvement

### ISSUE THREAD

**Issue by adityabhatia** [kyma-project/runtime-watcher#63]
Prepare E2E tests from creation watcher CR creation to processing it and deploying it in SKRs. Also cover multiple watcher CRs which are sequentially introduced, changed and deleted.

AC: 
- [ ]  Prepare E2E tests inside the runtime-watcher/kcp module

Use cases to be covered:
- [x] one watcher CR
- [x] several watcher CRs
- [x] watcher CR CRUD opeations 
- [x] listener event validation
- [x] invalid watcher CR
- [x] invalid watchable resource
- [x] spec watching
- [ ] status sub-resource watching

**Comment by janmedrek** [comment]
Waiting for: https://github.com/kyma-project/lifecycle-manager/issues/303
