### ISSUE TITLE
Deploy Runtime-Watcher to Control-Plane Environment

### ISSUE THREAD

**Issue by jakobmoellerdev** [kyma-project/runtime-watcher#74]
To ensure a proper a release flow, I need to ensure that deliveries can be done with kustomize easily and without problems. For this I need to integrate a kustomize enabled deployment into a Landscape and provide a guide on how to properly maintain it. One will also have to find automation capabilities:

- [ ] Have a working Kustomize Setup for a Control-Plane Deployment
- [ ] Have a small Guide setup that describes how to maintain the Control-Plane Deployment
- [ ] Propose a way to automate the setup and also multi-stage releases to dev/stage/prod

**Comment by tobiscr** [comment]
@khlifi411 : QQ - is this issue still required?
