### ISSUE TITLE
Evaluate networking resources for runtime-watcher

### ISSUE THREAD

**Issue by adityabhatia** [kyma-project/runtime-watcher#76]
## Description:
As part of this backlog item, enable mTLS communication between KCP and SKR watcher and implement certificate management for SKRs using Gardner features

## ACs:

- [x] Implement certificate issuing and management using Gardner certificate management
- [x] DNS Entry setup with primary and secondary domain names
- [x] Secured HTTPS hosting on KCP

**Comment by janmedrek** [comment]
Evaluation is done and results are documented in the PR.
