### ISSUE TITLE
Implement TLS secret lookup in the SKR watcher

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/runtime-watcher#93]
**Description**
Currently, the TLS secret lookup is implemented on the KCP side and passed as an argument to the SKR watcher deployment which mounts it as a volume. 
In this backlog item, the TLS secret lookup should be implemented as part of the SKR watcher's startup process.

**ACs**

- [ ] Implement secret lookup in the watcher startup process
- [ ] Implement fallback to environment values when secret lookup fails
- [ ] This about secret rotation

**Comment by janmedrek** [comment]
Waiting for the https://github.com/kyma-project/lifecycle-manager/issues/289

**Comment by janmedrek** [comment]
We do not need the lookup due to the architecture changes.
