### ISSUE TITLE
Enable `musttag` linter

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/runtime-watcher#96]
**Description**
The `musttag` linter has been disabled, because the lastest version of golangci-lint includes the 0.4.5 version, which has a major bug.

musttag already fixed that bug with version 0.5.0. But we need to wait until golangci-lint upgrades to the version 0.5.0 or higher. If that is done, the image of golangci-lint has to be upgraded in our pipelines. If that is done, we can re-enable it by removing the follwoing line: https://github.com/kyma-project/runtime-watcher/blob/main/skr/.golangci.yaml#L5

**ACs**
- [ ] enable `musttag` in the runtime-watcher/skr

**Comment by lindnerby** [comment]
musttag is now referenced with v0.6.0, unblocking this.
